version: '3'

services:
  mysql-container:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: container_mysql
    environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: mysql_db
